ALTER TYPE "TalentType" RENAME VALUE 'ASCENDED_VITALITY' TO 'AWAKENED_VITALITY';
ALTER TYPE "TalentType" RENAME VALUE 'ASCENDED_POWER' TO 'AWAKENED_POWER';
ALTER TYPE "TalentType" RENAME VALUE 'ASCENDED_RESILIENCE' TO 'AWAKENED_RESILIENCE';
