ALTER TYPE "ItemLocation" ADD VALUE 'BACKPACK' BEFORE 'EQUIPPED';
ALTER TYPE "ItemLocation" ADD VALUE 'LOST';
ALTER TYPE "ItemLineageType" ADD VALUE 'STORED_IN_CHEST' BEFORE 'EQUIPPED';
ALTER TYPE "ItemLineageType" ADD VALUE 'LOST_IN_BATTLE';
