ALTER TYPE "ResourceType" ADD VALUE IF NOT EXISTS 'HEALTH_POTION';
ALTER TYPE "ResourceType" ADD VALUE IF NOT EXISTS 'MANA_POTION';
ALTER TYPE "ResourceType" ADD VALUE IF NOT EXISTS 'DRYAD_HEARTWOOD';
